const routes = {
    login: '/oauth/token',
    employerSignup: '/employers/signup',
    userSignup: '/users/signup',
    accountVerify: '/accounts/verify',
    listIndustries: '/industries/list',
    employerProfile: '/employers/profile',
    userProfile: '/users/profile',
    userList: '/users/list',
    userJobScoring: '/jobpostings/job-scoring',
    userView: '/users/view',
    userUpdate: "/users/update",
    jobApply: "/jobpostings/apply",
    applicationsListForUser: "/jobpostings/applications/list-for-user",
    applicationsListForEmp: "/jobpostings/applications/list",
    userPhotoUpdate: "/users/update-photo",
    userResumeUpdate: "/users/update-doc-resume",
    userResumeDelete: "/users/delete-resume",
    userChooseDefaultResume: "/users/choose-default-resume",
    jobPostingCreate: '/jobpostings/create',
    jobPostingUpdate: '/jobpostings/update',
    skillTagList: '/skill-tags/list',
    forgotPassword: '/accounts/request-reset-password',
    jobPostingList: '/jobpostings/list',
    resetPassword: '/accounts/reset-password',
    jobDelete: '/jobpostings/delete',
    jobPostingView: '/jobpostings/view',
}

module.exports = routes;
